'use client'

import { useMemo, useState } from 'react'
import { Bell, ChevronDown, ChevronLeft, ChevronRight, Clock3, Heart, MapPin, Menu, Minus, Package, Plus, Search, ShoppingCart, Store, Trash2, Truck, X } from 'lucide-react'

type Product = { id: number; name: string; category: string; price: number; unit: string; stock: number; badge?: string; color: string }
const products: Product[] = [
  { id: 1, name: 'شوكولاتة ميلكا بالحليب', category: 'شوكولاتة', price: 230, unit: 'علبة', stock: 84, badge: 'الأكثر مبيعاً', color: 'bg-[#e9d8cc]' },
  { id: 2, name: 'بسكويت أوريو العائلي', category: 'بسكويت', price: 155, unit: 'كرتون', stock: 5, badge: 'عرض خاص', color: 'bg-[#dfe9f5]' },
  { id: 3, name: 'علكة ترايدنت نعناع', category: 'حلويات', price: 58, unit: 'كرتون', stock: 142, color: 'bg-[#d9ecdf]' },
  { id: 4, name: 'عصير راني برتقال 1 لتر', category: 'مشروبات', price: 120, unit: 'كرتون', stock: 0, color: 'bg-[#f6e6c5]' },
  { id: 5, name: 'شيبس تايجر جبنة', category: 'مقرمشات', price: 72, unit: 'كرتون', stock: 38, color: 'bg-[#f1d9d8]' },
  { id: 6, name: 'كاندي هاريبو جولد بير', category: 'حلويات', price: 260, unit: 'كرتون', stock: 67, badge: 'جديد', color: 'bg-[#e5daf0]' },
  { id: 7, name: 'قهوة محمصة فاخرة', category: 'بقالة', price: 310, unit: 'كرتون', stock: 24, color: 'bg-[#e4ded5]' },
  { id: 8, name: 'مياه معدنية 330 مل', category: 'مشروبات', price: 95, unit: 'كرتون', stock: 54, color: 'bg-[#dcecf1]' },
]
const categories = ['الكل', 'شوكولاتة', 'بسكويت', 'حلويات', 'مقرمشات', 'مشروبات', 'بقالة']
const money = (n: number) => `${n.toLocaleString('ar-DZ')} دج`

export default function StockManager() {
  const [query, setQuery] = useState(''); const [category, setCategory] = useState('الكل'); const [cart, setCart] = useState<Record<number, number>>({}); const [showCart, setShowCart] = useState(false); const [showMenu, setShowMenu] = useState(false); const [view, setView] = useState<'shop' | 'orders'>('shop'); const [toast, setToast] = useState('')
  const visible = products.filter(p => (category === 'الكل' || p.category === category) && p.name.includes(query))
  const cartItems = products.filter(p => cart[p.id]); const total = cartItems.reduce((sum, p) => sum + p.price * cart[p.id], 0); const count = Object.values(cart).reduce((a, b) => a + b, 0)
  const notify = (text: string) => { setToast(text); window.setTimeout(() => setToast(''), 2400) }
  const add = (id: number) => { setCart({ ...cart, [id]: (cart[id] || 0) + 1 }); notify('تمت إضافة المنتج إلى السلة') }
  const change = (id: number, delta: number) => setCart({ ...cart, [id]: Math.max(0, (cart[id] || 0) + delta) })
  return <div dir="rtl" className="min-h-screen bg-[#f6f8fb] font-sans text-[#172b4d]">
    <div className="bg-[#102a56] px-4 py-2 text-center text-xs text-white/90">شحن مجاني للطلبات التي تزيد عن 2,000 دج · أسعار خاصة لتجار الجملة</div>
    <header className="sticky top-0 z-30 border-b border-[#e5eaf0] bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center gap-5 px-4 py-4 lg:px-8"><button aria-label="فتح القائمة" className="lg:hidden" onClick={() => setShowMenu(true)}><Menu /></button><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-[#2f80ed] text-white"><Store className="size-5" /></div><div><p className="text-lg font-bold leading-none">شمس الضيافة</p><p className="mt-1 text-[11px] text-[#8190a5]">متجر الجملة للمواد الغذائية</p></div></div><nav className="hidden items-center gap-7 text-sm font-semibold lg:flex"><button onClick={() => setView('shop')} className="text-[#2f80ed]">الرئيسية</button>{categories.slice(1, 5).map(c => <button key={c} onClick={() => { setCategory(c); setView('shop') }} className="text-[#60738a] hover:text-[#2f80ed]">{c}</button>)}<button onClick={() => setView('orders')} className="text-[#60738a] hover:text-[#2f80ed]">تتبع الطلب</button></nav><div className="mr-auto flex items-center gap-2"><div className="relative hidden md:block"><Search className="absolute right-3 top-3 size-4 text-[#8190a5]" /><input aria-label="ابحث عن منتج" value={query} onChange={e => setQuery(e.target.value)} placeholder="ابحث عن منتج..." className="w-56 rounded-xl border border-[#e2e8f0] bg-[#f8fafc] py-2.5 pr-10 pl-3 text-sm outline-none focus:border-[#2f80ed]" /></div><button aria-label="المفضلة" className="rounded-xl p-2.5 text-[#60738a] hover:bg-[#f1f5f9]"><Heart className="size-5" /></button><button aria-label="السلة" onClick={() => setShowCart(true)} className="relative rounded-xl p-2.5 text-[#60738a] hover:bg-[#f1f5f9]"><ShoppingCart className="size-5" />{count > 0 && <span className="absolute -right-1 -top-1 grid size-5 place-items-center rounded-full bg-[#ef6262] text-[10px] text-white">{count}</span>}</button><button className="hidden rounded-xl bg-[#2f80ed] px-4 py-2.5 text-sm font-semibold text-white sm:block" onClick={() => notify('مرحباً بك في حسابك')}>تسجيل الدخول</button></div></div></header>
    {showMenu && <div className="fixed inset-0 z-50 bg-[#102a56] p-6 text-white lg:hidden"><button onClick={() => setShowMenu(false)}><X /></button><nav className="mt-10 flex flex-col gap-5 text-lg">{['الرئيسية', ...categories.slice(1), 'تتبع الطلب'].map(x => <button key={x} onClick={() => { setCategory(x === 'الرئيسية' ? 'الكل' : x); setView(x === 'تتبع الطلب' ? 'orders' : 'shop'); setShowMenu(false) }} className="text-right">{x}</button>)}</nav></div>}
    <main className="mx-auto max-w-7xl px-4 py-6 lg:px-8 lg:py-8">{view === 'shop' ? <><section className="relative overflow-hidden rounded-3xl bg-[#dcecff] px-6 py-10 sm:px-12 lg:px-16"><div className="max-w-xl"><p className="mb-3 inline-flex rounded-full bg-white/80 px-3 py-1 text-xs font-semibold text-[#2f80ed]">موسم العروض · كميات الجملة</p><h1 className="text-balance text-3xl font-extrabold leading-tight text-[#102a56] sm:text-5xl">كل ما يحتاجه متجرك<br /><span className="text-[#2f80ed]">في مكان واحد</span></h1><p className="mt-4 max-w-md text-sm leading-7 text-[#526984]">منتجات أصلية، أسعار منافسة، وتوصيل سريع إلى باب متجرك. اطلب الآن واستفد من عروض الجملة.</p><button onClick={() => document.getElementById('products')?.scrollIntoView({ behavior: 'smooth' })} className="mt-6 rounded-xl bg-[#2f80ed] px-6 py-3 text-sm font-bold text-white shadow-lg shadow-blue-200">تصفح المنتجات <ChevronLeft className="mr-1 inline size-4" /></button></div><div className="pointer-events-none absolute left-10 top-8 hidden text-[#2f80ed]/20 lg:block"><Package className="size-44" /></div></section><section className="my-8 grid grid-cols-2 gap-3 sm:grid-cols-4"><Info icon={Truck} title="توصيل سريع" text="لكل المدن" /><Info icon={Package} title="منتجات أصلية" text="ضمان الجودة" /><Info icon={Clock3} title="دعم متواصل" text="نحن هنا لمساعدتك" /><Info icon={MapPin} title="تغطية واسعة" text="كل أنحاء الوطن" /></section><section id="products"><div className="mb-5 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 className="text-2xl font-bold">منتجات مختارة لك</h2><p className="mt-1 text-sm text-[#8190a5]">اكتشف أفضل المنتجات بأسعار الجملة</p></div><div className="flex flex-wrap gap-2">{categories.map(c => <button key={c} onClick={() => setCategory(c)} className={`rounded-full px-4 py-2 text-xs font-semibold ${category === c ? 'bg-[#102a56] text-white' : 'bg-white text-[#60738a] ring-1 ring-[#e5eaf0]'}`}>{c}</button>)}</div></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{visible.map(p => <ProductCard key={p.id} product={p} amount={cart[p.id] || 0} onAdd={() => add(p.id)} onChange={d => change(p.id, d)} />)}</div>{visible.length === 0 && <div className="rounded-2xl bg-white p-12 text-center text-sm text-[#8190a5]">لا توجد منتجات تطابق بحثك</div>}</section></> : <Orders onNotify={notify} />}</main>
    {showCart && <Cart items={cartItems} cart={cart} total={total} onClose={() => setShowCart(false)} onChange={change} onCheckout={() => { setShowCart(false); setView('orders'); setCart({}); notify('تم إنشاء طلبك التجريبي بنجاح') }} />}{toast && <div role="status" className="fixed bottom-5 left-5 z-50 rounded-xl bg-[#102a56] px-5 py-3 text-sm text-white shadow-xl">{toast}</div>}
  </div>
}
function Info({ icon: Icon, title, text }: any) { return <div className="flex items-center gap-3 rounded-2xl bg-white p-4 shadow-sm"><div className="grid size-10 place-items-center rounded-xl bg-[#e8f1ff] text-[#2f80ed]"><Icon className="size-5" /></div><div><p className="text-sm font-bold">{title}</p><p className="mt-1 text-xs text-[#8190a5]">{text}</p></div></div> }
function ProductCard({ product: p, amount, onAdd, onChange }: { product: Product; amount: number; onAdd: () => void; onChange: (d: number) => void }) { return <article className="group overflow-hidden rounded-2xl border border-[#e6ebf1] bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className={`relative grid h-44 place-items-center ${p.color}`}><Package className="size-20 text-[#60738a]/35" />{p.badge && <span className="absolute right-3 top-3 rounded-full bg-white px-2.5 py-1 text-[10px] font-bold text-[#2f80ed] shadow-sm" >{p.badge}</span>}<button aria-label="أضف للمفضلة" className="absolute left-3 top-3 rounded-full bg-white/80 p-2 text-[#60738a]"><Heart className="size-4" /></button></div><div className="p-4"><p className="text-[11px] text-[#8190a5]">{p.category}</p><h3 className="mt-1 min-h-11 text-sm font-bold leading-6">{p.name}</h3><div className="mt-3 flex items-end justify-between"><div><p className="text-lg font-extrabold text-[#102a56]">{money(p.price)}</p><p className="text-[10px] text-[#8190a5]">لكل {p.unit}</p></div>{p.stock === 0 ? <span className="text-xs font-semibold text-[#ef6262]">نفد المخزون</span> : amount ? <div className="flex items-center gap-2 rounded-lg bg-[#eef5ff] p-1"><button aria-label="إنقاص الكمية" onClick={() => onChange(-1)} className="grid size-7 place-items-center rounded-md bg-white text-[#2f80ed]"><Minus className="size-3" /></button><span className="min-w-4 text-center text-xs font-bold">{amount}</span><button aria-label="زيادة الكمية" onClick={onAdd} className="grid size-7 place-items-center rounded-md bg-[#2f80ed] text-white"><Plus className="size-3" /></button></div> : <button onClick={onAdd} className="rounded-lg bg-[#2f80ed] p-2.5 text-white" aria-label="إضافة للسلة"><ShoppingCart className="size-4" /></button>}</div></div></article> }
function Cart({ items, cart, total, onClose, onChange, onCheckout }: any) { return <div className="fixed inset-0 z-50"><button aria-label="إغلاق السلة" className="absolute inset-0 bg-[#102a56]/40" onClick={onClose} /><aside className="absolute left-0 top-0 flex h-full w-full max-w-md flex-col bg-white shadow-2xl"><div className="flex items-center justify-between border-b p-5"><div><h2 className="font-bold">سلة التسوق</h2><p className="mt-1 text-xs text-[#8190a5]">{items.length} منتجات · {Object.values(cart).reduce((a: number, b: number) => a + b, 0)} قطعة</p></div><button onClick={onClose} aria-label="إغلاق"><X /></button></div><div className="flex-1 overflow-y-auto p-5">{items.length ? items.map((p: Product) => <div key={p.id} className="mb-4 flex items-center gap-3 border-b pb-4"><div className={`grid size-14 place-items-center rounded-xl ${p.color}`}><Package className="size-7 text-[#60738a]/45" /></div><div className="flex-1"><p className="text-sm font-bold">{p.name}</p><p className="mt-1 text-xs text-[#8190a5]">{money(p.price)}</p><div className="mt-2 flex items-center gap-2"><button onClick={() => onChange(p.id, -1)} className="rounded-md border p-1"><Minus className="size-3" /></button><span className="text-xs">{cart[p.id]}</span><button onClick={() => onChange(p.id, 1)} className="rounded-md border p-1"><Plus className="size-3" /></button></div></div><button aria-label="حذف المنتج" onClick={() => onChange(p.id, -cart[p.id])} className="text-[#ef6262]"><Trash2 className="size-4" /></button></div>) : <div className="py-20 text-center text-sm text-[#8190a5]">السلة فارغة<br /><span className="mt-2 block text-xs">أضف منتجات للبدء</span></div>}</div><div className="border-t p-5"><div className="mb-4 flex justify-between text-sm"><span className="text-[#8190a5]">الإجمالي</span><strong className="text-xl">{money(total)}</strong></div><button disabled={!items.length} onClick={onCheckout} className="w-full rounded-xl bg-[#2f80ed] py-3.5 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-40">إتمام الطلب</button></div></aside></div> }
function Orders({ onNotify }: { onNotify: (s: string) => void }) { const [number, setNumber] = useState(''); const [searched, setSearched] = useState(false); return <section className="mx-auto max-w-3xl"><div className="rounded-3xl bg-[#102a56] px-6 py-12 text-center text-white sm:px-12"><Truck className="mx-auto size-12 text-[#f4b740]" /><h1 className="mt-5 text-3xl font-bold">تتبع طلبك</h1><p className="mx-auto mt-3 max-w-md text-sm leading-7 text-blue-100">أدخل رقم الطلب لمعرفة حالته ومراحل التوصيل.</p><div className="mx-auto mt-7 flex max-w-md gap-2"><input value={number} onChange={e => setNumber(e.target.value)} placeholder="مثال: SM-2024-001" className="min-w-0 flex-1 rounded-xl px-4 py-3 text-sm text-[#172b4d] outline-none" /><button onClick={() => { setSearched(true); onNotify(number ? 'تم العثور على الطلب' : 'أدخل رقم الطلب أولاً') }} className="rounded-xl bg-[#f4b740] px-5 py-3 text-sm font-bold text-[#102a56]">تتبع</button></div></div>{searched && number && <div className="mt-6 rounded-2xl border border-[#e5eaf0] bg-white p-6"><div className="flex items-center justify-between"><div><p className="text-xs text-[#8190a5]">رقم الطلب</p><p className="mt-1 font-bold">{number}</p></div><span className="rounded-full bg-[#e3f6ec] px-3 py-1 text-xs font-bold text-[#188653]">قيد التجهيز</span></div><div className="mt-8 flex items-center justify-between"><Status label="تم الاستلام" active /><Status label="قيد التجهيز" active /><Status label="في الطريق" /><Status label="تم التسليم" /></div></div>}</section> }
function Status({ label, active }: { label: string; active?: boolean }) { return <div className="flex flex-col items-center gap-2 text-center"><span className={`grid size-7 place-items-center rounded-full text-xs ${active ? 'bg-[#2f80ed] text-white' : 'bg-[#e5eaf0] text-[#8190a5]'}`}>{active ? '✓' : ''}</span><span className="text-[10px] text-[#60738a]">{label}</span></div> }
